name: PR

on:
  pull_request:
    branches: [ prod, dev, staging, v2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8.4.0
      - uses: actions/checkout@v2
      - name: Get changed files 
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '
      - name: Show changed files
        run: echo ${{steps.get_file_changes.outputs.files}}
      - name: Build changed client
        if: contains(steps.get_file_changes.outputs.files, 'app/client')
        run: make build-docker-image-pr -e COMPONENT=client
      - name: Build changed api
        if: contains(steps.get_file_changes.outputs.files, 'app/api')
        run: make build-docker-image-pr -e COMPONENT=api